### ISSUE TITLE
Error message when nvim starts

### ISSUE THREAD

**Issue by pallymore** [bluz71/vim-nightfly-guicolors#17] opened 2021-05-07 13:46 UTC
Hi there - 

Just updated this plugin earlier today and now every time neovim launches I'm getting an error message (see screenshot below)

neovim version:  `NVIM v0.5.0-dev+1305-g21035cff9` 

![CleanShot 2021-05-07 at 09 41 18](https://user-images.githubusercontent.com/2566530/117459053-f639ef80-af18-11eb-99c0-92f34b4d9cac.png)

Thanks!

**Comment by jbyuki** [comment] 2021-05-07 14:11
Hi,
Sorry! That's caused by a PR I made earlier yesterday. It was supposed to fix something in a special case but I instead broke everything it seems. I will send a PR which fixes it.

**Comment by pallymore** [comment] 2021-05-07 14:16
> Hi,
> Sorry! That's caused by a PR I made earlier yesterday. It was supposed to fix something in a special case but I instead broke everything it seems. I will send a PR which fixes it.

No worries - hopefully it's gonna be an easy fix 😆

**Comment by bluz71** [comment] 2021-05-08 00:46
Merged.

My fault, I did not have time to test the previous PR yesterday, I eyeball'ed it and was satisfied. 

@jbyuki's newest PR does not error out so I am closing this.

**Closed by bluz71** 2021-05-08 00:46 UTC
