### ISSUE TITLE
Unused variables in TypeScript barely legible

### ISSUE THREAD

**Issue by wavded** [bluz71/vim-nightfly-guicolors#25] opened 2021-08-26 19:35 UTC
I'm running into this issue

<img width="222" alt="Screen Shot 2021-08-26 at 2 32 10 PM" src="https://user-images.githubusercontent.com/26638/131024646-20449a8e-35ce-4f5d-baa4-836f1659a886.png">

Testing other languages seems to be fine in this case.  I'm using coc.nvim.  I am using tree-sitter and do not have any other specific syntax plugins for TypeScript. Could something be interfering?

**Comment by bluz71** [comment] 2021-08-28 01:48
Thanks for debugging this.

It is confirmed that CoC is overlaying its own highlighting over the top of Treesitter.
I strongly believe this is **not** wanted, it does more harm than good especially since Treesitter does excellent highlighting by itself.

Quickly looking at CoC documentation lists these two options that you should experiment with:

- `g:coc_default_semantic_highlight_groups = 0`, this should already be defaulted to off in newer versions of CoC. Please double check at your end that symantic highlighting is disabled.

- [coc.preferences.colorSupport](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L796), this appears to be defaulted to true. This could be **the** problem. Please set this to false and try again.

Let me know which one works, I will then update the README here noting that CoC users should disable semantic highlighting or CoC color support.

Cheers.

**Comment by bluz71** [comment] 2021-08-30 02:22
@wavded,

Any updates on this? Did you manage to disable CoC highlighting?

Cheers.

**Comment by wavded** [comment] 2021-08-30 15:28
@bluz71 I just attempted these things:

> g:coc_default_semantic_highlight_groups = 0, this should already be defaulted to off in newer versions of CoC. Please double check at your end that symantic highlighting is disabled.

Setting this to `0` didn't make a difference.

> coc.preferences.colorSupport, this appears to be defaulted to true. This could be the problem. Please set this to false and try again.

Setting this to `false` also did not make a difference.

Seems the only thing that works so far is `hi link CocUnusedHighlight TSVariable` in my init.vim.

**Comment by bluz71** [comment] 2021-08-30 22:07
This genuinely seems like a fault with CoC.

It should not be highlighting anything if you do not want it to. If I were you I would open up an issue at the CoC issue tracker. This is very annoying of CoC, it is doing way too much, it seems silly of them to also be doing highlighting.

But it is up to you. If you gather some information, please let me know.

**Comment by bluz71** [comment] 2021-08-30 22:08
Closing this since this is a CoC issue. CoC should offer a working option to completely disable their own unwanted highlighting.

**Closed by bluz71** 2021-08-30 22:08 UTC

**Comment by bluz71** [comment] 2021-09-04 03:01
Another use has reported this Coc issue.

Hence, in this colorscheme I now link `CocUnusedHighlight` to White. So you shouldn't need your own link-fix anymore.

Are there any other Coc highlight issues I need to fix?

**Comment by wavded** [comment] 2021-09-05 21:05
Thx for the fix @bluz71, mine works well now without the fix I did.  I haven't noticed any other issues.
