### ISSUE TITLE
[BUG] When used with feline.nvim, the status line is displayed incorrectly when the window is split.

### ISSUE THREAD

**Issue by uga-rosa** [bluz71/vim-nightfly-guicolors#28] opened 2021-10-04 12:33 UTC
When used in conjunction with [feline.nvim](https://github.com/famiu/feline.nvim), the blank area in the status line becomes `^^^^^^^^` when splitting the window.

![image](https://user-images.githubusercontent.com/82267684/135851671-a925f8e2-eb26-4f62-bc96-3507252389dd.png)

This is minimal config.

init.vim
```vim
call plug#begin('/tmp/plugged')
Plug 'famiu/feline.nvim'
Plug 'bluz71/vim-nightfly-guicolors'
call plug#end()

lua require("feline").setup()

set termguicolors
colorscheme nightfly
```

**Comment by bluz71** [comment] 2021-10-06 04:41
Sorry for the late response, been very busy lately.

Anyway, If I comment out `StatusLineNC` the problem goes away. Except, `StatusLineNC` is a required highlight group (for my theme) and it is legitimately set as far as I can tell.

If I switch over to the [Embark](https://github.com/embark-theme/vim) colorscheme the same issue will result:

![Embark](https://user-images.githubusercontent.com/11382509/136141529-3c5d97cf-0c2b-409b-8e76-0a9d67c79803.png)

Hence, I believe the issue is with the feline plugin. I suggest opening up an issue with the feline maintainers, since it likely effects any colorscheme that sets `StatusLineNC`.

Closing here.

Best regards.

**Closed by bluz71** 2021-10-06 04:41 UTC

**Comment by uga-rosa** [comment] 2021-10-06 07:49
Thank you for looking into the cause!

**Comment by bluz71** [comment] 2021-10-06 08:05
No problem.

Hopefully the feline maintainers will fix this issue since it will effect many themes.

Cheers.
